FROM node:22-bookworm AS build
WORKDIR /src/web
ARG NUXT_PUBLIC_API_BASE=http://localhost:18081
ENV NUXT_PUBLIC_API_BASE=${NUXT_PUBLIC_API_BASE}
COPY web/package*.json ./
RUN npm install
COPY web/ ./
RUN npm run generate

FROM nginx:1.27-alpine
COPY deploy/nginx.conf /etc/nginx/conf.d/default.conf
RUN rm -rf /usr/share/nginx/html/*
COPY --from=build /src/web/.output/public/ /usr/share/nginx/html/
EXPOSE 18080
